final nowPlayingMock = {
  "dates": {"maximum": "2024-01-31", "minimum": "2023-12-20"},
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
      "genre_ids": [28, 12, 14],
      "id": 572802,
      "original_language": "en",
      "original_title": "Aquaman and the Lost Kingdom",
      "overview":
          "Agora mais temível do que nunca, Arraia Negra detém o poder do mítico Tridente Preto e sua ancestral força malévola. Para derrotá-lo, Aquaman recorrerá a seu irmão Orm, o ex-Rei da Atlântida, ainda na prisão, para forjar uma aliança improvável. Juntos, eles vão ter que deixar de lado suas diferenças para proteger seu reino, salvar a família de Aquaman e o mundo da irreversível destruição.",
      "popularity": 4197.714,
      "poster_path": "/84ispMxgLDRvQaA6zlM9i7sdAAI.jpg",
      "release_date": "2023-12-20",
      "title": "Aquaman 2: O Reino Perdido",
      "video": false,
      "vote_average": 6.879,
      "vote_count": 859
    },
    {
      "adult": false,
      "backdrop_path": "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
      "genre_ids": [35, 10751, 14],
      "id": 787699,
      "original_language": "en",
      "original_title": "Wonka",
      "overview":
          "Um jovem Willy Wonka embarca em uma missão para espalhar alegria por meio de seu chocolate, que rapidamente se torna um fenômeno.",
      "popularity": 3210.944,
      "poster_path": "/5IiODXjfLhVk5OhBlAqueCB4GQv.jpg",
      "release_date": "2023-12-06",
      "title": "Wonka",
      "video": false,
      "vote_average": 7.194,
      "vote_count": 1450
    },
    {
      "adult": false,
      "backdrop_path": "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      "genre_ids": [16, 12, 35, 10751, 28],
      "id": 940551,
      "original_language": "en",
      "original_title": "Migration",
      "overview":
          "Uma família de patos tenta convencer seu pai superprotetor a embarcar nas férias dos sonhos.",
      "popularity": 1655.989,
      "poster_path": "/2KPvdtGjeFT8IwxUkUWmifokXG0.jpg",
      "release_date": "2023-12-06",
      "title": "Patos!",
      "video": false,
      "vote_average": 7.849,
      "vote_count": 225
    },
    {
      "adult": false,
      "backdrop_path": "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      "genre_ids": [16, 10751, 14, 12],
      "id": 1022796,
      "original_language": "en",
      "original_title": "Wish",
      "overview":
          "No reino mágico de Rosas, Asha é uma moça perspicaz que faz um desejo tão poderoso que é atendido por uma força cósmica: uma pequena esfera de energia ilimitada chamada Star. Juntas, Asha e Star enfrentam o Rei Magnifico pra salvar a comunidade e provar que, quando um ser humano se une à energia das estrelas, coisas maravilhosas podem acontecer.",
      "popularity": 1176.469,
      "poster_path": "/tImBlStZQ9NYFZ7Hbik53vui3Sf.jpg",
      "release_date": "2023-11-13",
      "title": "Wish: O Poder dos Desejos",
      "video": false,
      "vote_average": 6.497,
      "vote_count": 390
    },
    {
      "adult": false,
      "backdrop_path": "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
      "genre_ids": [28, 35, 80],
      "id": 955916,
      "original_language": "en",
      "original_title": "Lift",
      "overview":
          "Uma equipe internacional de ladrões liderada por Cyrus Whitaker corre contra o tempo para roubar 500 milhões de dólares em barras de ouro de um avião a mais de 12 mil metros de altitude.",
      "popularity": 906.25,
      "poster_path": "/ca74jjIYRVDdsnlWk8JzyVY49dE.jpg",
      "release_date": "2024-01-10",
      "title": "Lift: Roubo nas Alturas",
      "video": false,
      "vote_average": 6.425,
      "vote_count": 511
    },
    {
      "adult": false,
      "backdrop_path": "/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg",
      "genre_ids": [18, 36],
      "id": 906126,
      "original_language": "es",
      "original_title": "La sociedad de la nieve",
      "overview":
          "Em 13 de outubro de 1972, o voo 571 da Força Aérea Uruguaia, fretado para levar um time de rúgbi ao Chile, cai em uma geleira no coração da Cordilheira dos Andes.",
      "popularity": 863.788,
      "poster_path": "/7fQTmvKgVGxifieVryqqlxohkoW.jpg",
      "release_date": "2023-12-13",
      "title": "A Sociedade da Neve",
      "video": false,
      "vote_average": 8.071,
      "vote_count": 1353
    },
    {
      "adult": false,
      "backdrop_path": "/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg",
      "genre_ids": [28, 35, 10749],
      "id": 848187,
      "original_language": "en",
      "original_title": "Role Play",
      "overview":
          "Emma e Dave apimentam seu aniversário de casamento com uma noite disfarçados em Nova York. Mas as coisas se tornam perigosas quando a vida secreta de Emma como assassina de aluguel, que Dave desconhece, é exposta por Bob, colocando sua família em risco. Emma terá que contar com suas habilidades letais e determinação para proteger a família a todo custo.",
      "popularity": 615.769,
      "poster_path": "/d9O2dIxU1X8Qc8s8kf9RFiiDMMB.jpg",
      "release_date": "2023-12-14",
      "title": "O Jogo do Disfarce",
      "video": false,
      "vote_average": 5.815,
      "vote_count": 200
    },
    {
      "adult": false,
      "backdrop_path": "/6OnoMgGFuZ921eV8v8yEyXoag19.jpg",
      "genre_ids": [28, 53],
      "id": 1211957,
      "original_language": "en",
      "original_title": "The Painter",
      "overview":
          "The Painter é um filme de suspense de ação americano de 2024 dirigido por Kimani Ray Smith e escrito por Brian Buccellato. É estrelado por Charlie Weber, Jon Voight, Marie Avgeropoulos e Madison Bailey. The Painter foi lançado nos Estados Unidos em 5 de janeiro de 2024",
      "popularity": 630.616,
      "poster_path": "/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg",
      "release_date": "2024-01-05",
      "title": "The Painter",
      "video": false,
      "vote_average": 5.868,
      "vote_count": 19
    },
    {
      "adult": false,
      "backdrop_path": "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      "genre_ids": [18, 36],
      "id": 872585,
      "original_language": "en",
      "original_title": "Oppenheimer",
      "overview":
          "A história do físico americano J. Robert Oppenheimer, seu papel no Projeto Manhattan e no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, e o quanto isso mudaria a história do mundo para sempre.",
      "popularity": 536.381,
      "poster_path": "/c0DCmfC7Et2K3URnIJ4ahJpeXR2.jpg",
      "release_date": "2023-07-19",
      "title": "Oppenheimer",
      "video": false,
      "vote_average": 8.117,
      "vote_count": 6352
    },
    {
      "adult": false,
      "backdrop_path": "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
      "genre_ids": [16, 12, 14],
      "id": 508883,
      "original_language": "ja",
      "original_title": "君たちはどう生きるか",
      "overview":
          "Depois de perder a mãe durante a guerra, o jovem Mahito muda-se para a propriedade de sua família no campo. Lá, uma série de eventos misteriosos o levam a uma torre antiga e isolada, lar de uma travessa garça cinzenta. Quando a nova madrasta de Mahito desaparece, ele segue a garça até a torre e entra num mundo fantástico partilhado pelos vivos e pelos mortos. Ao embarcar em uma jornada épica com a garça como guia, Mahito deve descobrir os segredos deste mundo e a verdade sobre si mesmo.",
      "popularity": 554.29,
      "poster_path": "/qPNmxw9Ag66rmaYPKDpob9HIpth.jpg",
      "release_date": "2023-07-14",
      "title": "O Menino e a Garça",
      "video": false,
      "vote_average": 7.454,
      "vote_count": 812
    },
    {
      "adult": false,
      "backdrop_path": "/h0oBqUpax591vOacpBsDJ8cynjk.jpg",
      "genre_ids": [878, 10749, 35],
      "id": 792307,
      "original_language": "en",
      "original_title": "Poor Things",
      "overview":
          "A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.",
      "popularity": 530.655,
      "poster_path": "/kTbBzzdVICzzbv9iFaX0aadvjg0.jpg",
      "release_date": "2023-12-07",
      "title": "Pobres Criaturas",
      "video": false,
      "vote_average": 8.151,
      "vote_count": 354
    },
    {
      "adult": false,
      "backdrop_path": "/ay0PJQZizDXk0pzhoGX4v7K9h7A.jpg",
      "genre_ids": [28, 53],
      "id": 1214314,
      "original_language": "en",
      "original_title": "One More Shot",
      "overview":
          "Após o ataque ao local negro na Polónia, o SEAL da Marinha Jake Harris é condenado a escoltar o suspeito terrorista Amin Mansur a Washington DC para interrogatório.",
      "popularity": 401.306,
      "poster_path": "/zkHkMLoC41euiPZG62wslcHLreH.jpg",
      "release_date": "2024-01-12",
      "title": "Mais Um Tiro Certo",
      "video": false,
      "vote_average": 6.682,
      "vote_count": 77
    },
    {
      "adult": false,
      "backdrop_path": "/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg",
      "genre_ids": [35, 10749],
      "id": 1072790,
      "original_language": "en",
      "original_title": "Anyone But You",
      "overview":
          "Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.",
      "popularity": 427.938,
      "poster_path": "/f5e8cT4vBQ1ZRSXC658CvUnzzkl.jpg",
      "release_date": "2023-12-21",
      "title": "Todos Menos Você",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 110
    },
    {
      "adult": false,
      "backdrop_path": "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      "genre_ids": [28, 53],
      "id": 866398,
      "original_language": "en",
      "original_title": "The Beekeeper",
      "overview":
          "Clay está em busca de vingança e não vai parar até acabar com o sistema criminoso responsável pela morte de sua amiga. O plano brutal de Clay, um ex-agente de uma organização secreta poderosa conhecida como “Beekeepers”, ganha dimensões nacionais envolvendo governos e as instituições mais influentes do mundo. Determinado a fazer justiça com suas próprias mãos, ele está disposto a tudo e não vai poupar ninguém para concluir seu plano.",
      "popularity": 403.52,
      "poster_path": "/cCGFvoxzaBbYM3I68s6F939fybN.jpg",
      "release_date": "2024-01-10",
      "title": "Beekeeper - Rede de Vingança",
      "video": false,
      "vote_average": 7.424,
      "vote_count": 177
    },
    {
      "adult": false,
      "backdrop_path": "/klb3yODwKMRle19EcvdeSatEZL7.jpg",
      "genre_ids": [27, 53],
      "id": 1072342,
      "original_language": "en",
      "original_title": "Night Swim",
      "overview": "",
      "popularity": 395.711,
      "poster_path": "/uwDBPf2fD7v7rBwX6I0h3ehF7vp.jpg",
      "release_date": "2024-01-03",
      "title": "Mergulho Noturno",
      "video": false,
      "vote_average": 5.7,
      "vote_count": 115
    },
    {
      "adult": false,
      "backdrop_path": "/adNMDatnEnIEo4LUo1KyhouP6VA.jpg",
      "genre_ids": [28, 18],
      "id": 1212073,
      "original_language": "de",
      "original_title": "60 Minuten",
      "overview":
          "Desesperado para não perder a guarda da filha, um lutador de MMA abandona uma luta importante e corre por Berlim para chegar à festa de aniversário da menina.",
      "popularity": 519.634,
      "poster_path": "/n5wjsuYh954HLagCnqrLpPT8xi7.jpg",
      "release_date": "2024-01-19",
      "title": "60 Minutos",
      "video": false,
      "vote_average": 6.861,
      "vote_count": 104
    },
    {
      "adult": false,
      "backdrop_path": "/47SVqaO02doJ06tOmrjiWDkwU3T.jpg",
      "genre_ids": [28, 53],
      "id": 927107,
      "original_language": "en",
      "original_title": "The Bricklayer",
      "overview":
          "Em The Bricklayer, alguém está chantageando a CIA - assassinando jornalistas estrangeiros e fazendo parecer que a agência é a responsável. À medida que o mundo começa a se unir contra os EUA, a CIA deve atrair seu agente mais brilhante - e rebelde - para fora da aposentadoria, forçando-o a confrontar seu passado duvidoso enquanto desvenda uma conspiração internacional.",
      "popularity": 344.154,
      "poster_path": "/pwOQ9lqLX1OgsJRSybS662wMcu8.jpg",
      "release_date": "2023-12-14",
      "title": "The Bricklayer",
      "video": false,
      "vote_average": 6.276,
      "vote_count": 67
    },
    {
      "adult": false,
      "backdrop_path": "/e0M3WVJm4nBrAg0LbJq0gdKi3U7.jpg",
      "genre_ids": [18, 878, 28],
      "id": 695721,
      "original_language": "en",
      "original_title": "The Hunger Games: The Ballad of Songbirds & Snakes",
      "overview":
          "Anos antes de se tornar o tirânico presidente de Panem, Coriolanus Snow aos 18 anos vê uma chance de mudança de sorte quando é escolhido para ser mentor de Lucy Gray Baird, a garota tributo do empobrecido Distrito 12.",
      "popularity": 368.018,
      "poster_path": "/9fWIhZDRKOv0ad75f3G2ZsRnkp.jpg",
      "release_date": "2023-11-15",
      "title": "Jogos Vorazes: A Cantiga dos Pássaros e das Serpentes",
      "video": false,
      "vote_average": 7.224,
      "vote_count": 1581
    },
    {
      "adult": false,
      "backdrop_path": "/rVJfabCz1ViynQCEz54MRqdZig1.jpg",
      "genre_ids": [16, 878, 28],
      "id": 1155089,
      "original_language": "en",
      "original_title": "Justice League: Crisis on Infinite Earths Part One",
      "overview":
          "A morte está chegando. Pior do que a morte: o esquecimento. Não apenas para a nossa Terra, mas para todos, em todos os lugares, em cada universo! Contra essa destruição definitiva, o misterioso Monitor reuniu a maior equipe de Super-Heróis já montada. Mas o que a força combinada de Superman, Mulher Maravilha, Batman, Flash, Lanterna Verde e centenas de Super-Heróis de múltiplas Terras pode fazer para salvar toda a realidade de um armagedom de antimatéria imparável?!",
      "popularity": 339.448,
      "poster_path": "/vsiDOIO4APrPQQ4xx8vJW8N0uHV.jpg",
      "release_date": "2024-01-09",
      "title": "Liga da Justiça: Crise nas Infinitas Terras - Parte 1",
      "video": false,
      "vote_average": 7.763,
      "vote_count": 131
    },
    {
      "adult": false,
      "backdrop_path": "/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
      "genre_ids": [878, 27, 28],
      "id": 940721,
      "original_language": "ja",
      "original_title": "ゴジラ-1.0",
      "overview":
          "Em um Japão social e economicamente devastado após o término da Segunda Guerra Mundial, a situação chega a um nível ainda mais crítico quando uma gigantesca e misteriosa criatura surge do mar para assolar o país.",
      "popularity": 325.492,
      "poster_path": "/iXrCBynsyRGbOtoBeWjt1bRINuA.jpg",
      "release_date": "2023-11-03",
      "title": "Godzilla Minus One",
      "video": false,
      "vote_average": 7.9,
      "vote_count": 354
    }
  ],
  "total_pages": 158,
  "total_results": 3142
};

final discoverMock = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
      "genre_ids": [28, 12, 14],
      "id": 572802,
      "original_language": "en",
      "original_title": "Aquaman and the Lost Kingdom",
      "overview":
          "Agora mais temível do que nunca, Arraia Negra detém o poder do mítico Tridente Preto e sua ancestral força malévola. Para derrotá-lo, Aquaman recorrerá a seu irmão Orm, o ex-Rei da Atlântida, ainda na prisão, para forjar uma aliança improvável. Juntos, eles vão ter que deixar de lado suas diferenças para proteger seu reino, salvar a família de Aquaman e o mundo da irreversível destruição.",
      "popularity": 4197.714,
      "poster_path": "/84ispMxgLDRvQaA6zlM9i7sdAAI.jpg",
      "release_date": "2023-12-20",
      "title": "Aquaman 2: O Reino Perdido",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 828
    },
    {
      "adult": false,
      "backdrop_path": "/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg",
      "genre_ids": [35, 10751, 14],
      "id": 787699,
      "original_language": "en",
      "original_title": "Wonka",
      "overview":
          "Um jovem Willy Wonka embarca em uma missão para espalhar alegria por meio de seu chocolate, que rapidamente se torna um fenômeno.",
      "popularity": 3210.944,
      "poster_path": "/5IiODXjfLhVk5OhBlAqueCB4GQv.jpg",
      "release_date": "2023-12-06",
      "title": "Wonka",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 1433
    },
    {
      "adult": false,
      "backdrop_path": "/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg",
      "genre_ids": [878, 12, 28],
      "id": 609681,
      "original_language": "en",
      "original_title": "The Marvels",
      "overview":
          "Quando suas obrigações a levam a uma fenda espacial anômala ligada a um revolucionário Kree, os poderes de Carol Danvers, a Capitã Marvel, se entrelaçam aos de Kamala Khan, a Ms. Marvel, e aos da sobrinha de Carol, astronauta da S.A.B.E.R., Capitã Monica Rambeau. Juntas, esse trio improvável deve ser unir para salvar o universo como \"As Marvels\".",
      "popularity": 1807.709,
      "poster_path": "/gmtrDKIKXRFkChgHGALZTiKDVo0.jpg",
      "release_date": "2023-11-08",
      "title": "As Marvels",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 1214
    },
    {
      "adult": false,
      "backdrop_path": "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      "genre_ids": [16, 12, 35, 10751, 28],
      "id": 940551,
      "original_language": "en",
      "original_title": "Migration",
      "overview":
          "Uma família de patos tenta convencer seu pai superprotetor a embarcar nas férias dos sonhos.",
      "popularity": 1655.989,
      "poster_path": "/2KPvdtGjeFT8IwxUkUWmifokXG0.jpg",
      "release_date": "2023-12-06",
      "title": "Patos!",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 216
    },
    {
      "adult": false,
      "backdrop_path": "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      "genre_ids": [16, 10751, 14, 12],
      "id": 1022796,
      "original_language": "en",
      "original_title": "Wish",
      "overview":
          "No reino mágico de Rosas, Asha é uma moça perspicaz que faz um desejo tão poderoso que é atendido por uma força cósmica: uma pequena esfera de energia ilimitada chamada Star. Juntas, Asha e Star enfrentam o Rei Magnifico pra salvar a comunidade e provar que, quando um ser humano se une à energia das estrelas, coisas maravilhosas podem acontecer.",
      "popularity": 1176.469,
      "poster_path": "/tImBlStZQ9NYFZ7Hbik53vui3Sf.jpg",
      "release_date": "2023-11-13",
      "title": "Wish: O Poder dos Desejos",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 383
    },
    {
      "adult": false,
      "backdrop_path": "/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg",
      "genre_ids": [28, 878, 53],
      "id": 799155,
      "original_language": "hi",
      "original_title": "Attack",
      "overview":
          "Depois de perder tudo devido a um ataque terrorista, o ex-agente do governo Arjun Shergill participa de um projeto que o torna um supersoldado.",
      "popularity": 953.035,
      "poster_path": "/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg",
      "release_date": "2022-04-01",
      "title": "Missão Ataque",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 38
    },
    {
      "adult": false,
      "backdrop_path": "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
      "genre_ids": [28, 35, 80],
      "id": 955916,
      "original_language": "en",
      "original_title": "Lift",
      "overview":
          "Uma equipe internacional de ladrões liderada por Cyrus Whitaker corre contra o tempo para roubar 500 milhões de dólares em barras de ouro de um avião a mais de 12 mil metros de altitude.",
      "popularity": 906.25,
      "poster_path": "/ca74jjIYRVDdsnlWk8JzyVY49dE.jpg",
      "release_date": "2024-01-10",
      "title": "Lift: Roubo nas Alturas",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 507
    },
    {
      "adult": false,
      "backdrop_path": "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
      "genre_ids": [36, 10752, 18],
      "id": 753342,
      "original_language": "en",
      "original_title": "Napoleon",
      "overview":
          "Um olhar pessoal sobre as origens do líder militar francês e sua rápida e implacável ascensão a imperador. A história é vista através do prisma do relacionamento dependente e volátil de Napoleão com sua esposa e amor verdadeiro, Josefina.",
      "popularity": 891.144,
      "poster_path": "/oaUS0YJN3cHpvin1BMNmmnv0gRX.jpg",
      "release_date": "2023-11-22",
      "title": "Napoleão",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 1411
    },
    {
      "adult": false,
      "backdrop_path": "/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg",
      "genre_ids": [18, 36],
      "id": 906126,
      "original_language": "es",
      "original_title": "La sociedad de la nieve",
      "overview":
          "Em 13 de outubro de 1972, o voo 571 da Força Aérea Uruguaia, fretado para levar um time de rúgbi ao Chile, cai em uma geleira no coração da Cordilheira dos Andes.",
      "popularity": 863.788,
      "poster_path": "/7fQTmvKgVGxifieVryqqlxohkoW.jpg",
      "release_date": "2023-12-13",
      "title": "A Sociedade da Neve",
      "video": false,
      "vote_average": 8.1,
      "vote_count": 1340
    },
    {
      "adult": false,
      "backdrop_path": "/nAQpXoqurOdVdFSEdYramsVF33w.jpg",
      "genre_ids": [28, 53],
      "id": 1211957,
      "original_language": "en",
      "original_title": "The Painter",
      "overview":
          "The Painter é um filme de suspense de ação americano de 2024 dirigido por Kimani Ray Smith e escrito por Brian Buccellato. É estrelado por Charlie Weber, Jon Voight, Marie Avgeropoulos e Madison Bailey. The Painter foi lançado nos Estados Unidos em 5 de janeiro de 2024",
      "popularity": 630.616,
      "poster_path": "/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg",
      "release_date": "2024-01-05",
      "title": "The Painter",
      "video": false,
      "vote_average": 5.9,
      "vote_count": 19
    },
    {
      "adult": false,
      "backdrop_path": "/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg",
      "genre_ids": [28, 35, 10749],
      "id": 848187,
      "original_language": "en",
      "original_title": "Role Play",
      "overview":
          "Emma e Dave apimentam seu aniversário de casamento com uma noite disfarçados em Nova York. Mas as coisas se tornam perigosas quando a vida secreta de Emma como assassina de aluguel, que Dave desconhece, é exposta por Bob, colocando sua família em risco. Emma terá que contar com suas habilidades letais e determinação para proteger a família a todo custo.",
      "popularity": 615.769,
      "poster_path": "/d9O2dIxU1X8Qc8s8kf9RFiiDMMB.jpg",
      "release_date": "2023-12-14",
      "title": "O Jogo do Disfarce",
      "video": false,
      "vote_average": 5.8,
      "vote_count": 196
    },
    {
      "adult": false,
      "backdrop_path": "/ruKNVJFViAyR4jguVboFXTskMOe.jpg",
      "genre_ids": [53, 28, 27],
      "id": 1028703,
      "original_language": "en",
      "original_title": "The OctoGames",
      "overview": "",
      "popularity": 564.488,
      "poster_path": "/qGz5rffXhegQH5PGUDiObqoOt06.jpg",
      "release_date": "2022-10-07",
      "title": "The OctoGames",
      "video": false,
      "vote_average": 4.8,
      "vote_count": 32
    },
    {
      "adult": false,
      "backdrop_path": "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
      "genre_ids": [16, 12, 14],
      "id": 508883,
      "original_language": "ja",
      "original_title": "君たちはどう生きるか",
      "overview":
          "Depois de perder a mãe durante a guerra, o jovem Mahito muda-se para a propriedade de sua família no campo. Lá, uma série de eventos misteriosos o levam a uma torre antiga e isolada, lar de uma travessa garça cinzenta. Quando a nova madrasta de Mahito desaparece, ele segue a garça até a torre e entra num mundo fantástico partilhado pelos vivos e pelos mortos. Ao embarcar em uma jornada épica com a garça como guia, Mahito deve descobrir os segredos deste mundo e a verdade sobre si mesmo.",
      "popularity": 554.29,
      "poster_path": "/qPNmxw9Ag66rmaYPKDpob9HIpth.jpg",
      "release_date": "2023-07-14",
      "title": "O Menino e a Garça",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 809
    },
    {
      "adult": false,
      "backdrop_path": "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      "genre_ids": [18, 36],
      "id": 872585,
      "original_language": "en",
      "original_title": "Oppenheimer",
      "overview":
          "A história do físico americano J. Robert Oppenheimer, seu papel no Projeto Manhattan e no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, e o quanto isso mudaria a história do mundo para sempre.",
      "popularity": 536.381,
      "poster_path": "/c0DCmfC7Et2K3URnIJ4ahJpeXR2.jpg",
      "release_date": "2023-07-19",
      "title": "Oppenheimer",
      "video": false,
      "vote_average": 8.1,
      "vote_count": 6341
    },
    {
      "adult": false,
      "backdrop_path": "/h0oBqUpax591vOacpBsDJ8cynjk.jpg",
      "genre_ids": [878, 10749, 35],
      "id": 792307,
      "original_language": "en",
      "original_title": "Poor Things",
      "overview":
          "A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.",
      "popularity": 530.655,
      "poster_path": "/kTbBzzdVICzzbv9iFaX0aadvjg0.jpg",
      "release_date": "2023-12-07",
      "title": "Pobres Criaturas",
      "video": false,
      "vote_average": 8.1,
      "vote_count": 337
    },
    {
      "adult": false,
      "backdrop_path": "/adNMDatnEnIEo4LUo1KyhouP6VA.jpg",
      "genre_ids": [28, 18],
      "id": 1212073,
      "original_language": "de",
      "original_title": "60 Minuten",
      "overview":
          "Desesperado para não perder a guarda da filha, um lutador de MMA abandona uma luta importante e corre por Berlim para chegar à festa de aniversário da menina.",
      "popularity": 519.634,
      "poster_path": "/n5wjsuYh954HLagCnqrLpPT8xi7.jpg",
      "release_date": "2024-01-19",
      "title": "60 Minutos",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 98
    },
    {
      "adult": false,
      "backdrop_path": "/dvNrgldueQciabkYmlCnyhmaPoO.jpg",
      "genre_ids": [28, 9648, 53, 27],
      "id": 899445,
      "original_language": "en",
      "original_title": "Deep Fear",
      "overview":
          "Navegando sozinha pelo Caribe num barco a vela, uma mulher enfrenta perigos dentro e fora d'água quando sua viagem se torna uma luta por sobrevivência.",
      "popularity": 462.675,
      "poster_path": "/1ZZFTMqbQaP59yGTqKOcfqVE7NC.jpg",
      "release_date": "2023-10-18",
      "title": "Terror nas Profundezas",
      "video": false,
      "vote_average": 5.3,
      "vote_count": 76
    },
    {
      "adult": false,
      "backdrop_path": "/oQ429AcD85ttxvOxAaYpETnAsW0.jpg",
      "genre_ids": [28, 10752],
      "id": 918692,
      "original_language": "ru",
      "original_title": "Гранит",
      "overview":
          "O Estado Islâmico destruiu a vila dos irmãos Jose e Luis no sudeste da África. O irmão mais velho se junta a organização, mas o mais novo consegue escapar e é encontrado por militares russos. Ele agora teme que ao revelar a localização do grupo terrorista, está colocando a vida de seu irmão em perigo.",
      "popularity": 450.497,
      "poster_path": "/4LLBtwwAqMfou51XQax0Axr2dSo.jpg",
      "release_date": "2021-12-29",
      "title": "Lados Opostos",
      "video": false,
      "vote_average": 6,
      "vote_count": 8
    },
    {
      "adult": false,
      "backdrop_path": "/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg",
      "genre_ids": [35, 10749],
      "id": 1072790,
      "original_language": "en",
      "original_title": "Anyone But You",
      "overview":
          "Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.",
      "popularity": 427.938,
      "poster_path": "/f5e8cT4vBQ1ZRSXC658CvUnzzkl.jpg",
      "release_date": "2023-12-21",
      "title": "Todos Menos Você",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 109
    },
    {
      "adult": false,
      "backdrop_path": "/vUusbRUPQjU85z3mq9rp2r1GYvf.jpg",
      "genre_ids": [28, 53],
      "id": 924763,
      "original_language": "en",
      "original_title": "Weekend Warriors",
      "overview": "",
      "popularity": 422.076,
      "poster_path": "/uGyZZODYqcYINRPIgaHbMmawQ2I.jpg",
      "release_date": "2021-04-01",
      "title": "Weekend Warriors",
      "video": false,
      "vote_average": 7,
      "vote_count": 3
    }
  ],
  "total_pages": 42157,
  "total_results": 843134
};

final popularMock = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
      "genre_ids": [28, 12, 14],
      "id": 572802,
      "original_language": "en",
      "original_title": "Aquaman and the Lost Kingdom",
      "overview":
          "Agora mais temível do que nunca, Arraia Negra detém o poder do mítico Tridente Preto e sua ancestral força malévola. Para derrotá-lo, Aquaman recorrerá a seu irmão Orm, o ex-Rei da Atlântida, ainda na prisão, para forjar uma aliança improvável. Juntos, eles vão ter que deixar de lado suas diferenças para proteger seu reino, salvar a família de Aquaman e o mundo da irreversível destruição.",
      "popularity": 4197.714,
      "poster_path": "/84ispMxgLDRvQaA6zlM9i7sdAAI.jpg",
      "release_date": "2023-12-20",
      "title": "Aquaman 2: O Reino Perdido",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 858
    },
    {
      "adult": false,
      "backdrop_path": "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
      "genre_ids": [35, 10751, 14],
      "id": 787699,
      "original_language": "en",
      "original_title": "Wonka",
      "overview":
          "Um jovem Willy Wonka embarca em uma missão para espalhar alegria por meio de seu chocolate, que rapidamente se torna um fenômeno.",
      "popularity": 3210.944,
      "poster_path": "/5IiODXjfLhVk5OhBlAqueCB4GQv.jpg",
      "release_date": "2023-12-06",
      "title": "Wonka",
      "video": false,
      "vote_average": 7.193,
      "vote_count": 1448
    },
    {
      "adult": false,
      "backdrop_path": "/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg",
      "genre_ids": [878, 12, 28],
      "id": 609681,
      "original_language": "en",
      "original_title": "The Marvels",
      "overview":
          "Quando suas obrigações a levam a uma fenda espacial anômala ligada a um revolucionário Kree, os poderes de Carol Danvers, a Capitã Marvel, se entrelaçam aos de Kamala Khan, a Ms. Marvel, e aos da sobrinha de Carol, astronauta da S.A.B.E.R., Capitã Monica Rambeau. Juntas, esse trio improvável deve ser unir para salvar o universo como \"As Marvels\".",
      "popularity": 1807.709,
      "poster_path": "/gmtrDKIKXRFkChgHGALZTiKDVo0.jpg",
      "release_date": "2023-11-08",
      "title": "As Marvels",
      "video": false,
      "vote_average": 6.37,
      "vote_count": 1222
    },
    {
      "adult": false,
      "backdrop_path": "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      "genre_ids": [16, 12, 35, 10751, 28],
      "id": 940551,
      "original_language": "en",
      "original_title": "Migration",
      "overview":
          "Uma família de patos tenta convencer seu pai superprotetor a embarcar nas férias dos sonhos.",
      "popularity": 1655.989,
      "poster_path": "/2KPvdtGjeFT8IwxUkUWmifokXG0.jpg",
      "release_date": "2023-12-06",
      "title": "Patos!",
      "video": false,
      "vote_average": 7.849,
      "vote_count": 225
    },
    {
      "adult": false,
      "backdrop_path": "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      "genre_ids": [16, 10751, 14, 12],
      "id": 1022796,
      "original_language": "en",
      "original_title": "Wish",
      "overview":
          "No reino mágico de Rosas, Asha é uma moça perspicaz que faz um desejo tão poderoso que é atendido por uma força cósmica: uma pequena esfera de energia ilimitada chamada Star. Juntas, Asha e Star enfrentam o Rei Magnifico pra salvar a comunidade e provar que, quando um ser humano se une à energia das estrelas, coisas maravilhosas podem acontecer.",
      "popularity": 1176.469,
      "poster_path": "/tImBlStZQ9NYFZ7Hbik53vui3Sf.jpg",
      "release_date": "2023-11-13",
      "title": "Wish: O Poder dos Desejos",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 389
    },
    {
      "adult": false,
      "backdrop_path": "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
      "genre_ids": [28, 35, 80],
      "id": 955916,
      "original_language": "en",
      "original_title": "Lift",
      "overview":
          "Uma equipe internacional de ladrões liderada por Cyrus Whitaker corre contra o tempo para roubar 500 milhões de dólares em barras de ouro de um avião a mais de 12 mil metros de altitude.",
      "popularity": 906.25,
      "poster_path": "/ca74jjIYRVDdsnlWk8JzyVY49dE.jpg",
      "release_date": "2024-01-10",
      "title": "Lift: Roubo nas Alturas",
      "video": false,
      "vote_average": 6.425,
      "vote_count": 511
    },
    {
      "adult": false,
      "backdrop_path": "/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg",
      "genre_ids": [28, 878, 53],
      "id": 799155,
      "original_language": "hi",
      "original_title": "Attack",
      "overview":
          "Depois de perder tudo devido a um ataque terrorista, o ex-agente do governo Arjun Shergill participa de um projeto que o torna um supersoldado.",
      "popularity": 953.035,
      "poster_path": "/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg",
      "release_date": "2022-04-01",
      "title": "Missão Ataque",
      "video": false,
      "vote_average": 7.026,
      "vote_count": 39
    },
    {
      "adult": false,
      "backdrop_path": "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
      "genre_ids": [36, 10752, 18],
      "id": 753342,
      "original_language": "en",
      "original_title": "Napoleon",
      "overview":
          "Um olhar pessoal sobre as origens do líder militar francês e sua rápida e implacável ascensão a imperador. A história é vista através do prisma do relacionamento dependente e volátil de Napoleão com sua esposa e amor verdadeiro, Josefina.",
      "popularity": 891.144,
      "poster_path": "/oaUS0YJN3cHpvin1BMNmmnv0gRX.jpg",
      "release_date": "2023-11-22",
      "title": "Napoleão",
      "video": false,
      "vote_average": 6.49,
      "vote_count": 1419
    },
    {
      "adult": false,
      "backdrop_path": "/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg",
      "genre_ids": [18, 36],
      "id": 906126,
      "original_language": "es",
      "original_title": "La sociedad de la nieve",
      "overview":
          "Em 13 de outubro de 1972, o voo 571 da Força Aérea Uruguaia, fretado para levar um time de rúgbi ao Chile, cai em uma geleira no coração da Cordilheira dos Andes.",
      "popularity": 863.788,
      "poster_path": "/7fQTmvKgVGxifieVryqqlxohkoW.jpg",
      "release_date": "2023-12-13",
      "title": "A Sociedade da Neve",
      "video": false,
      "vote_average": 8.069,
      "vote_count": 1352
    },
    {
      "adult": false,
      "backdrop_path": "/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg",
      "genre_ids": [28, 35, 10749],
      "id": 848187,
      "original_language": "en",
      "original_title": "Role Play",
      "overview":
          "Emma e Dave apimentam seu aniversário de casamento com uma noite disfarçados em Nova York. Mas as coisas se tornam perigosas quando a vida secreta de Emma como assassina de aluguel, que Dave desconhece, é exposta por Bob, colocando sua família em risco. Emma terá que contar com suas habilidades letais e determinação para proteger a família a todo custo.",
      "popularity": 615.769,
      "poster_path": "/d9O2dIxU1X8Qc8s8kf9RFiiDMMB.jpg",
      "release_date": "2023-12-14",
      "title": "O Jogo do Disfarce",
      "video": false,
      "vote_average": 5.815,
      "vote_count": 200
    },
    {
      "adult": false,
      "backdrop_path": "/6OnoMgGFuZ921eV8v8yEyXoag19.jpg",
      "genre_ids": [28, 53],
      "id": 1211957,
      "original_language": "en",
      "original_title": "The Painter",
      "overview":
          "The Painter é um filme de suspense de ação americano de 2024 dirigido por Kimani Ray Smith e escrito por Brian Buccellato. É estrelado por Charlie Weber, Jon Voight, Marie Avgeropoulos e Madison Bailey. The Painter foi lançado nos Estados Unidos em 5 de janeiro de 2024",
      "popularity": 630.616,
      "poster_path": "/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg",
      "release_date": "2024-01-05",
      "title": "The Painter",
      "video": false,
      "vote_average": 5.868,
      "vote_count": 19
    },
    {
      "adult": false,
      "backdrop_path": "/ruKNVJFViAyR4jguVboFXTskMOe.jpg",
      "genre_ids": [53, 28, 27],
      "id": 1028703,
      "original_language": "en",
      "original_title": "The OctoGames",
      "overview": "",
      "popularity": 564.488,
      "poster_path": "/qGz5rffXhegQH5PGUDiObqoOt06.jpg",
      "release_date": "2022-10-07",
      "title": "The OctoGames",
      "video": false,
      "vote_average": 4.636,
      "vote_count": 33
    },
    {
      "adult": false,
      "backdrop_path": "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      "genre_ids": [18, 36],
      "id": 872585,
      "original_language": "en",
      "original_title": "Oppenheimer",
      "overview":
          "A história do físico americano J. Robert Oppenheimer, seu papel no Projeto Manhattan e no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, e o quanto isso mudaria a história do mundo para sempre.",
      "popularity": 536.381,
      "poster_path": "/c0DCmfC7Et2K3URnIJ4ahJpeXR2.jpg",
      "release_date": "2023-07-19",
      "title": "Oppenheimer",
      "video": false,
      "vote_average": 8.118,
      "vote_count": 6351
    },
    {
      "adult": false,
      "backdrop_path": "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
      "genre_ids": [16, 12, 14],
      "id": 508883,
      "original_language": "ja",
      "original_title": "君たちはどう生きるか",
      "overview":
          "Depois de perder a mãe durante a guerra, o jovem Mahito muda-se para a propriedade de sua família no campo. Lá, uma série de eventos misteriosos o levam a uma torre antiga e isolada, lar de uma travessa garça cinzenta. Quando a nova madrasta de Mahito desaparece, ele segue a garça até a torre e entra num mundo fantástico partilhado pelos vivos e pelos mortos. Ao embarcar em uma jornada épica com a garça como guia, Mahito deve descobrir os segredos deste mundo e a verdade sobre si mesmo.",
      "popularity": 554.29,
      "poster_path": "/qPNmxw9Ag66rmaYPKDpob9HIpth.jpg",
      "release_date": "2023-07-14",
      "title": "O Menino e a Garça",
      "video": false,
      "vote_average": 7.454,
      "vote_count": 812
    },
    {
      "adult": false,
      "backdrop_path": "/h0oBqUpax591vOacpBsDJ8cynjk.jpg",
      "genre_ids": [878, 10749, 35],
      "id": 792307,
      "original_language": "en",
      "original_title": "Poor Things",
      "overview":
          "A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.",
      "popularity": 530.655,
      "poster_path": "/kTbBzzdVICzzbv9iFaX0aadvjg0.jpg",
      "release_date": "2023-12-07",
      "title": "Pobres Criaturas",
      "video": false,
      "vote_average": 8.149,
      "vote_count": 353
    },
    {
      "adult": false,
      "backdrop_path": "/oQ429AcD85ttxvOxAaYpETnAsW0.jpg",
      "genre_ids": [28, 10752],
      "id": 918692,
      "original_language": "ru",
      "original_title": "Гранит",
      "overview":
          "O Estado Islâmico destruiu a vila dos irmãos Jose e Luis no sudeste da África. O irmão mais velho se junta a organização, mas o mais novo consegue escapar e é encontrado por militares russos. Ele agora teme que ao revelar a localização do grupo terrorista, está colocando a vida de seu irmão em perigo.",
      "popularity": 450.497,
      "poster_path": "/4LLBtwwAqMfou51XQax0Axr2dSo.jpg",
      "release_date": "2021-12-29",
      "title": "Lados Opostos",
      "video": false,
      "vote_average": 6.0,
      "vote_count": 8
    },
    {
      "adult": false,
      "backdrop_path": "/dvNrgldueQciabkYmlCnyhmaPoO.jpg",
      "genre_ids": [28, 9648, 53, 27],
      "id": 899445,
      "original_language": "en",
      "original_title": "Deep Fear",
      "overview":
          "Navegando sozinha pelo Caribe num barco a vela, uma mulher enfrenta perigos dentro e fora d'água quando sua viagem se torna uma luta por sobrevivência.",
      "popularity": 462.675,
      "poster_path": "/1ZZFTMqbQaP59yGTqKOcfqVE7NC.jpg",
      "release_date": "2023-10-18",
      "title": "Terror nas Profundezas",
      "video": false,
      "vote_average": 5.3,
      "vote_count": 76
    },
    {
      "adult": false,
      "backdrop_path": "/ay0PJQZizDXk0pzhoGX4v7K9h7A.jpg",
      "genre_ids": [28, 53],
      "id": 1214314,
      "original_language": "en",
      "original_title": "One More Shot",
      "overview":
          "Após o ataque ao local negro na Polónia, o SEAL da Marinha Jake Harris é condenado a escoltar o suspeito terrorista Amin Mansur a Washington DC para interrogatório.",
      "popularity": 401.306,
      "poster_path": "/zkHkMLoC41euiPZG62wslcHLreH.jpg",
      "release_date": "2024-01-12",
      "title": "Mais Um Tiro Certo",
      "video": false,
      "vote_average": 6.682,
      "vote_count": 77
    },
    {
      "adult": false,
      "backdrop_path": "/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg",
      "genre_ids": [35, 10749],
      "id": 1072790,
      "original_language": "en",
      "original_title": "Anyone But You",
      "overview":
          "Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.",
      "popularity": 427.938,
      "poster_path": "/f5e8cT4vBQ1ZRSXC658CvUnzzkl.jpg",
      "release_date": "2023-12-21",
      "title": "Todos Menos Você",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 110
    },
    {
      "adult": false,
      "backdrop_path": "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      "genre_ids": [28, 53],
      "id": 866398,
      "original_language": "en",
      "original_title": "The Beekeeper",
      "overview":
          "Clay está em busca de vingança e não vai parar até acabar com o sistema criminoso responsável pela morte de sua amiga. O plano brutal de Clay, um ex-agente de uma organização secreta poderosa conhecida como “Beekeepers”, ganha dimensões nacionais envolvendo governos e as instituições mais influentes do mundo. Determinado a fazer justiça com suas próprias mãos, ele está disposto a tudo e não vai poupar ninguém para concluir seu plano.",
      "popularity": 403.52,
      "poster_path": "/cCGFvoxzaBbYM3I68s6F939fybN.jpg",
      "release_date": "2024-01-10",
      "title": "Beekeeper - Rede de Vingança",
      "video": false,
      "vote_average": 7.424,
      "vote_count": 177
    }
  ],
  "total_pages": 42486,
  "total_results": 849704
};

final upcomingMock = {
  "dates": {"maximum": "2024-02-21", "minimum": "2024-01-31"},
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
      "genre_ids": [35, 10751, 14],
      "id": 787699,
      "original_language": "en",
      "original_title": "Wonka",
      "overview":
          "Um jovem Willy Wonka embarca em uma missão para espalhar alegria por meio de seu chocolate, que rapidamente se torna um fenômeno.",
      "popularity": 3210.944,
      "poster_path": "/5IiODXjfLhVk5OhBlAqueCB4GQv.jpg",
      "release_date": "2023-12-06",
      "title": "Wonka",
      "video": false,
      "vote_average": 7.189,
      "vote_count": 1454
    },
    {
      "adult": false,
      "backdrop_path": "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      "genre_ids": [16, 12, 35, 10751, 28],
      "id": 940551,
      "original_language": "en",
      "original_title": "Migration",
      "overview":
          "Uma família de patos tenta convencer seu pai superprotetor a embarcar nas férias dos sonhos.",
      "popularity": 1655.989,
      "poster_path": "/2KPvdtGjeFT8IwxUkUWmifokXG0.jpg",
      "release_date": "2023-12-06",
      "title": "Patos!",
      "video": false,
      "vote_average": 7.841,
      "vote_count": 227
    },
    {
      "adult": false,
      "backdrop_path": "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
      "genre_ids": [16, 12, 14],
      "id": 508883,
      "original_language": "ja",
      "original_title": "君たちはどう生きるか",
      "overview":
          "Depois de perder a mãe durante a guerra, o jovem Mahito muda-se para a propriedade de sua família no campo. Lá, uma série de eventos misteriosos o levam a uma torre antiga e isolada, lar de uma travessa garça cinzenta. Quando a nova madrasta de Mahito desaparece, ele segue a garça até a torre e entra num mundo fantástico partilhado pelos vivos e pelos mortos. Ao embarcar em uma jornada épica com a garça como guia, Mahito deve descobrir os segredos deste mundo e a verdade sobre si mesmo.",
      "popularity": 554.29,
      "poster_path": "/qPNmxw9Ag66rmaYPKDpob9HIpth.jpg",
      "release_date": "2023-07-14",
      "title": "O Menino e a Garça",
      "video": false,
      "vote_average": 7.452,
      "vote_count": 813
    },
    {
      "adult": false,
      "backdrop_path": "/h0oBqUpax591vOacpBsDJ8cynjk.jpg",
      "genre_ids": [878, 10749, 35],
      "id": 792307,
      "original_language": "en",
      "original_title": "Poor Things",
      "overview":
          "A jovem Bella Baxter é trazida de volta à vida pelo cientista Dr. Godwin Baxter. Querendo ver mais do mundo, ela foge com um advogado e viaja pelos continentes. Livre dos preconceitos de sua época, Bella exige igualdade e libertação.",
      "popularity": 530.655,
      "poster_path": "/kTbBzzdVICzzbv9iFaX0aadvjg0.jpg",
      "release_date": "2023-12-07",
      "title": "Pobres Criaturas",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 354
    },
    {
      "adult": false,
      "backdrop_path": "/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg",
      "genre_ids": [35, 10749],
      "id": 1072790,
      "original_language": "en",
      "original_title": "Anyone But You",
      "overview":
          "Bea e Ben parecem o casal perfeito, mas depois de um primeiro encontro incrível, algo acontece que transforma sua atração ardente em gelo - até que eles se encontram inesperadamente juntos em um casamento na Austrália.  Então eles fazem o que dois adultos maduros fariam: fingem ser um casal.",
      "popularity": 427.938,
      "poster_path": "/f5e8cT4vBQ1ZRSXC658CvUnzzkl.jpg",
      "release_date": "2023-12-21",
      "title": "Todos Menos Você",
      "video": false,
      "vote_average": 7.232,
      "vote_count": 110
    },
    {
      "adult": false,
      "backdrop_path": "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
      "genre_ids": [28, 53],
      "id": 866398,
      "original_language": "en",
      "original_title": "The Beekeeper",
      "overview":
          "Clay está em busca de vingança e não vai parar até acabar com o sistema criminoso responsável pela morte de sua amiga. O plano brutal de Clay, um ex-agente de uma organização secreta poderosa conhecida como “Beekeepers”, ganha dimensões nacionais envolvendo governos e as instituições mais influentes do mundo. Determinado a fazer justiça com suas próprias mãos, ele está disposto a tudo e não vai poupar ninguém para concluir seu plano.",
      "popularity": 403.52,
      "poster_path": "/cCGFvoxzaBbYM3I68s6F939fybN.jpg",
      "release_date": "2024-01-10",
      "title": "Beekeeper - Rede de Vingança",
      "video": false,
      "vote_average": 7.438,
      "vote_count": 178
    },
    {
      "adult": false,
      "backdrop_path": "/klb3yODwKMRle19EcvdeSatEZL7.jpg",
      "genre_ids": [27, 53],
      "id": 1072342,
      "original_language": "en",
      "original_title": "Night Swim",
      "overview": "",
      "popularity": 395.711,
      "poster_path": "/uwDBPf2fD7v7rBwX6I0h3ehF7vp.jpg",
      "release_date": "2024-01-03",
      "title": "Mergulho Noturno",
      "video": false,
      "vote_average": 5.7,
      "vote_count": 115
    },
    {
      "adult": false,
      "backdrop_path": "/9uNCYl2qmg16FLarg3n3Ea0PBIG.jpg",
      "genre_ids": [27, 53],
      "id": 1216784,
      "original_language": "en",
      "original_title": "Sunrise",
      "overview": "",
      "popularity": 387.653,
      "poster_path": "/4aRvg2ybz646gciX5M6qaclunC2.jpg",
      "release_date": "2024-01-19",
      "title": "Sunrise",
      "video": false,
      "vote_average": 4.0,
      "vote_count": 2
    },
    {
      "adult": false,
      "backdrop_path": "/p9DKeXp6FPJtAQ1k13Z4zPWrCbN.jpg",
      "genre_ids": [18],
      "id": 1058694,
      "original_language": "en",
      "original_title": "Radical",
      "overview": "",
      "popularity": 302.331,
      "poster_path": "/eSatbygYZp8ooprBHZdb6GFZxGB.jpg",
      "release_date": "2023-10-19",
      "title": "Radical",
      "video": false,
      "vote_average": 8.2,
      "vote_count": 33
    },
    {
      "adult": false,
      "backdrop_path": "/hQJR85HLngbthcWvaBXsaNCntvl.jpg",
      "genre_ids": [18, 10749],
      "id": 1226281,
      "original_language": "tl",
      "original_title": "Pantasya ni Tami",
      "overview": "",
      "popularity": 297.861,
      "poster_path": "/o1kk7iwp8x2TDq80HpUkVn9kxqL.jpg",
      "release_date": "2024-02-02",
      "title": "Pantasya ni Tami",
      "video": false,
      "vote_average": 0.0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/7NRGAtu8E4343NSKwhkgmVRDINw.jpg",
      "genre_ids": [27, 9648],
      "id": 507089,
      "original_language": "en",
      "original_title": "Five Nights at Freddy's",
      "overview":
          "Enquanto passa sua primeira noite no trabalho, um problemático guarda de segurança da Pizzaria Freddy Fazbear logo percebe que não será uma tarefa fácil sobreviver ao seu primeiro turno.",
      "popularity": 293.53,
      "poster_path": "/1yUbmAiw2cUSpyXNIaiST7JzCtG.jpg",
      "release_date": "2023-10-25",
      "title": "Five Nights at Freddy's - O Pesadelo Sem Fim",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 3251
    },
    {
      "adult": false,
      "backdrop_path": "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
      "genre_ids": [28, 35],
      "id": 897087,
      "original_language": "en",
      "original_title": "Freelance",
      "overview":
          "Um ex-agente das forças especiais trabalha fornecendo segurança para uma jornalista que está entrevistando um ditador. No meio da entrevista, ocorre um golpe militar e eles são forçados a fugir para a selva, onde precisam sobreviver.",
      "popularity": 284.383,
      "poster_path": "/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
      "release_date": "2023-10-05",
      "title": "Freelance",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 484
    },
    {
      "adult": false,
      "backdrop_path": "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
      "genre_ids": [28, 18],
      "id": 678512,
      "original_language": "en",
      "original_title": "Sound of Freedom",
      "overview":
          "A história de Tim Ballard, um ex-agente do governo dos EUA, que largou seu emprego para dedicar sua vida a resgatar crianças de traficantes sexuais globais.",
      "popularity": 226.556,
      "poster_path": "/hwOHbymoAhjrMx7v5ShHCNIP4NI.jpg",
      "release_date": "2023-07-03",
      "title": "Som da Liberdade",
      "video": false,
      "vote_average": 8.051,
      "vote_count": 1841
    },
    {
      "adult": false,
      "backdrop_path": "/fGe1ej335XbqN1j9teoDpofpbLX.jpg",
      "genre_ids": [18, 9648],
      "id": 915935,
      "original_language": "fr",
      "original_title": "Anatomie d'une chute",
      "overview":
          "Uma mulher é suspeita do assassinato de seu marido, e seu filho cego enfrenta um dilema moral como única testemunha.",
      "popularity": 208.618,
      "poster_path": "/7lw13cpje1kXtb1d46qZAgmq7ff.jpg",
      "release_date": "2023-08-13",
      "title": "Anatomia de Uma Queda",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 732
    },
    {
      "adult": false,
      "backdrop_path": "/4W11akSpZBp8O09cQFEO0lqmVJl.jpg",
      "genre_ids": [18, 36],
      "id": 365620,
      "original_language": "en",
      "original_title": "Ferrari",
      "overview":
          "O ex-piloto de corrida, Enzo Ferrari está em crise. A falência assombra a empresa que ele e sua mulher, Laura, construíram do nada 10 anos atrás. O casamento tempestuoso dos dois sofre com o luto pela morte de um filho e a dificuldade de reconhecer outro. Ele decide contrapor essas perdas apostando tudo em uma corrida - a icônica Mille Miglia, na Itália.",
      "popularity": 190.604,
      "poster_path": "/xBFyJHvXCTgf9Vmq5uCnXRHrMQ4.jpg",
      "release_date": "2023-12-14",
      "title": "Ferrari",
      "video": false,
      "vote_average": 6.747,
      "vote_count": 231
    },
    {
      "adult": false,
      "backdrop_path": "/mpIpHN7DJprENGiSvxOaG5mLzht.jpg",
      "genre_ids": [35],
      "id": 673593,
      "original_language": "en",
      "original_title": "Mean Girls",
      "overview":
          "A adolescente Cady Heron foi educada na África pelos seus pais cientistas. Quando sua família se muda para o subúrbio, nos Estados Unidos, Cady começa a frequentar a escola pública e recebe uma rápida introdução às leis de popularidade que dividem seus colegas. Sem querer, ela acaba no meio de um grupo de elite de estudantes apelidadas “as poderosas”.",
      "popularity": 172.369,
      "poster_path": "/qb4gIc5tqc7M7iQDcye6JINFHmC.jpg",
      "release_date": "2024-01-10",
      "title": "Meninas Malvadas",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 95
    },
    {
      "adult": false,
      "backdrop_path": "/mv8M0PqQYicndU7TGgBAHrI4uUo.jpg",
      "genre_ids": [27, 53],
      "id": 744857,
      "original_language": "es",
      "original_title": "Cuando acecha la maldad",
      "overview":
          "Em uma vila remota, dois irmãos encontram um homem possuído por demônios prestes a dar à luz ao mal encarnado. Eles decidem se livrar do sujeito, mas acabam apenas espalhando o caos.",
      "popularity": 167.902,
      "poster_path": "/tkfFo9lKYVGd8tBYipaPgJvN2AI.jpg",
      "release_date": "2023-10-05",
      "title": "O Mal que Nos Habita",
      "video": false,
      "vote_average": 7.35,
      "vote_count": 460
    },
    {
      "adult": false,
      "backdrop_path": "/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg",
      "genre_ids": [10749, 18],
      "id": 820525,
      "original_language": "en",
      "original_title": "After Everything",
      "overview":
          "Hardin não para de pensar na sua relação conturbada com Tessa. Vítima de um bloqueio criativo, o jovem escritor resolve fazer as malas e partir para Lisboa, capital portuguesa, onde espera reencontrar a sua inspiração.",
      "popularity": 167.856,
      "poster_path": "/jxb7NBx8jjqxiz3MIE3KMyqp45d.jpg",
      "release_date": "2023-09-13",
      "title": "After: Para Sempre",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 663
    },
    {
      "adult": false,
      "backdrop_path": "/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg",
      "genre_ids": [35, 18],
      "id": 840430,
      "original_language": "en",
      "original_title": "The Holdovers",
      "overview":
          "Acompanha a desventura de um professor mal-humorado de uma prestigiada escola americana, forçado a permanecer no campus para cuidar do grupo de alunos que não tem para onde ir durante as férias de Natal. Ele acaba criando um vínculo improvável com um deles - um encrenqueiro magoado e muito inteligente - e com o cozinheiro-chefe da escola, que acaba de perder um filho no Vietnã.",
      "popularity": 159.662,
      "poster_path": "/zbn5UGlHK4z7UIBliBtvg6hUGNn.jpg",
      "release_date": "2023-10-27",
      "title": "Os Rejeitados",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 524
    },
    {
      "adult": false,
      "backdrop_path": "/50stq3Jlny6oEgJjsXbQvbajCNw.jpg",
      "genre_ids": [10749, 18],
      "id": 1020006,
      "original_language": "en",
      "original_title": "Priscilla",
      "overview":
          "Quando Priscilla Beaulieu conheceu Elvis Presley, ele já era a grande estrela do rock que conhecemos, mas logo se revela uma pessoa completamente para Priscilla: um aliado durante momentos ruins, um amigo que se pode contar e claro, uma grande paixão.",
      "popularity": 141.477,
      "poster_path": "/gn5Qt8X7cltcYC5HYBXgLQZEogM.jpg",
      "release_date": "2023-10-27",
      "title": "Priscilla",
      "video": false,
      "vote_average": 7.0,
      "vote_count": 315
    }
  ],
  "total_pages": 38,
  "total_results": 747
};
