///if you need a PageController, you need implement init and dispose to
///not create abandoned garbage generated by stream
abstract class InterfacePageController {
  void init() async {}

  void dispose() async {}
}
